sample/projectFolder/objects/Account.object
<CustomObject>
    <fields>
        <fullName>company_name__c</fullName>
        <label>company_name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/projectFolder/objects/Company_apps__c.object
<CustomObject>
    <fields>
        <fullName>app_category__c</fullName>
        <label>app category</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>app_id__c</fullName>
        <label>app_id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>company_name__c</fullName>
        <label>company name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>current_download__c</fullName>
        <label>current download</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>current_revenue__c</fullName>
        <label>current revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>previous_week_download__c</fullName>
        <label>previous week download</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>previous_week_revenue__c</fullName>
        <label>previous week revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>APP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company_apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/projectFolder/classes/Find_apps.cls
public class Find_apps {
    String company_name;
    List<Company_apps__c> apps_list= new List<Company_apps__c>();
    public Find_apps(){
        String account_id = ApexPages.currentPage().getParameters().get('id');
        if (account_id != Null)
        {
            company_name = 
            [SELECT Company_name__c FROM Account WHERE Id = :account_id].company_name__c;
        
        //use : to refer var
        apps_list = 
            [SELECT Name,app_category__c,app_id__c,current_download__c,current_revenue__c,
             previous_week_download__c,previous_week_revenue__c 
             FROM Company_apps__c WHERE Company_name__c = :company_name];
        }
        else{
             apps_list = 
            [SELECT Name,app_category__c,app_id__c,current_download__c,current_revenue__c,
             previous_week_download__c,previous_week_revenue__c 
             FROM Company_apps__c];
        }
}
    public List<Company_apps__c> getapps(){
        return apps_list;
    }
    public String getcompany_name(){
        return company_name;
    }
}